### PR TITLE
Android O Required Changes

### PR DESCRIPTION
**Pull request by klinker41**
This switches the library to use explicit broadcasts when an action has been completed instead of implicit. Effectively, this means that it should work correctly on Android O with their background changes.

The main idea here is that instead of relying on the intent-filter for registering the receiver, the library will look up the correct class in the manifest based on the taskAffinity for the receiver. This allows us to then find the correct receiver and explicitly broadcast to only that receiver to save on battery power.

@klinker24 what do you think of this approach? I've tested with the sample app and it seems to be working correctly, but the sample isn't very robust and it's tough to be sure. After taking a look to make sure the implementation looks good to you, let's release version 4.0.0-alpha1 and import that into Pulse to actually test it. That way we'll be able to check to make sure that SMS and MMS statuses (sent, delivered, failed, etc) are adjusting as expected.

### CODE REVIEW

**Comment by klinker24** [comment]
Little bit of a unique use of `taskAffinity` (usually for activities, right?), but I have no problem with these changes, they are all very straight-forward. 

I see why you want to keep the receivers, instead of changing to services to do this: it keeps the code almost the same, and just makes for some manifest changes. Would these things make more sense to be done in `IntentService` s though, since they are run on a background thread? If so, I think that now is the time to change it, since we are breaking the API anyways, with the major release.

Switching to `IntentService` could use the same `taskAffinity` method, it would just start a service, instead of sending out a broadcast. Any thoughts behind that and why you went with `taskAffinity` instead of a permission declaration? I guess I don't have a great grasp on declaring permissions, I assume it would be similar to the `taskAffinity` though.'

Definitely would like to try it out, in Pulse, before merging this one, but 👍 in terms of code, and the changes!

**Comment by klinker41** [comment]
I didn't want to switch to service just so that any subclasses don't need to be changed by our users. Wanted to make it as painless as possible and for most of the broadcasts it doesn't matter what thread they run on.

As for the permissions, I read the documentation and found it confusing and not well documented. I didn't want to make people add permissions for all of the broadcasts. I thought the task affinity documentation wasn't good either, but that seemed like it didn't matter as much and wouldn't have big consequences in the end.

Ideally I wanted to just read the intent filters from each receiver and work off of that, but there was no method for getting the actions from the receiver that I could find. If I did it like that, then there wouldn't have even been any required changes.

**Comment by klinker24** [comment]
Fair enough. It all looks like it will work to me, so that shouldn't be an issue. I say cut a snapshot and we can test tomorrow!

**Comment by klinker24** [comment]
I put out a snapshot and loaded it into Pulse. I am going to test it out, without targeting Android O, first. Will post some results

**Comment by klinker41** [comment]
SGTM. I haven't been able to get O targets compiling on my computer yet. Presumably need the Android studio 2.4 update I guess.

**Comment by klinker24** [comment]
Yes, you do. They send fine, and receive fine, but looks like you forgot to update the `MMS_SENT` broadcast: https://github.com/klinker41/android-smsmms/blob/android-o/library/src/main/java/com/klinker/android/send_message/Transaction.java#L568

They are never marked as sent, because this broadcast is still expecting to be implicit

**Comment by klinker41** [comment]
@klinker24 I completed the changes there, you can check and see if they work in Pulse again. Another note, do we need to do the same for the SMS sent and delivered notifications or did those work correctly? They are done the same way as the MMS_SENT one, so you should definitely test that and make sure they are working as expected.

**Comment by klinker24** [comment]
Well, they are definitely getting marked as sent correctly, but you are definitely right that they should be converted... Not sure how it is working, to be honest?

**Comment by klinker41** [comment]
Those are probably being registered dynamically instead of through the manifest? I don't remember, but I'll switch them over as well.

**Comment by klinker24** [comment]
With the latest changes, it is working when targeting SDK 25! Will test over the next few days, then see if I can cut to building against Android O

**Comment by klinker41** [comment]
Great, thanks for testing.

**Pull request merged**
