### PR TITLE
Remove unused imports, Annotate APIs

### PR DESCRIPTION
**Pull request by LoungeKatt**
This is mostly cleaning for Android Studio

### CODE REVIEW

**Comment by klinker41** [comment]
Can you use the build constants for API versions? `Build.VERSION_CODES.LOLLIPOP` for example.

**Comment by LoungeKatt** [comment]
Is there any benefit to adding an imported value over using something that does not require a specific API to be present? In terms of memory, it is more or less a wasted reference.

**Comment by klinker24** [comment]
Maybe, but it is considered best practice to use constants when available. I have no doubt that these constants will never change, but it is still much clearer to anyone else coming into the code.

**Comment by klinker41** [comment]
Just easier to read and then I don't have to memorize the values. I believe that when you compile, it gets switched to the literal value anyways, so no harm in adding it.

**Comment by LoungeKatt** [comment]
@klinker24 It's not best practice. It's readability. There is significant difference when talking about annotations versus inline conditionals. This is strictly a compiler annotation.
@klinker41 I was pretty sure that was your reason, but I was waiting to see if there was another. I didn't see a risk, being as you added the identifier to each method name. 
`@TargetApi(23)
      private static <T> T ensureRouteToMmsNetworkMarshmallow(Context context, Task<T> task) throws IOException {`
When you compile it, it is not even included. This was the reason to avoid importing anything for conversion that will remain in the compiled product for something that is discarded.

I can change it, but I suggest looking into annotations. It is a bit unsettling to think an entire team wasn't really aware of their purpose.

**Comment by klinker41** [comment]
I disagree with you, you should absolutely use constants whenever they are available. That is a best practice for both readability and maintainability.

**Comment by klinker24** [comment]
I would actually definitely consider readability to be a best practice. You don't agree? Especially for an open source project and any enterprise projects. It is extremely important to make it easy on others that come into the code base.

I think that an import is well worth it and see no reason at all not to include it here. Not sure

**Comment by LoungeKatt** [comment]
I said this before. It is an annotation on a method that already specified the build identifier to reference the API (number) and avoid a "requires API x but you have set minimum y". 
Best practice is to minimize the impact of compiler conditionals on the compiled code. I understand your preference, but trying to leverage best practice simply to sound correct is poor judgement. If you were aware of best practices, these annotations would have been present.

**Comment by klinker24** [comment]
A best practice is to maximize readability. Software is definitely not always about optimization. If it was, no one new would ever be able to come into a project, without a massive ramp up period.

There are many different types of software projects, where different "best practices" can and should be applied. Adding that constant will have zero affect on the final outcome of this library and its performance, so it is absolutely a best practice, and a no brainer, here.

[Clean Code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) is a fantastic book from one of the most reputable developers ever, if you have never checked it out before. 

http://alvinalexander.com/programming/clean-code-quotes-robert-c-martin

He has a major focus on readable code:

> Most comments are not needed, and if you feel the need to write a comment, you should consider rewriting your code to make it more readable.

This is a situation where a comment would have been warrented, to describe to someone new to the code base what `21` represented. With this tiny tweak, that comment is no longer necessary, the code is 100% more readable because of that. So yes, I do consider clean, readable code, to be a best practice, and I will always take that over an unused import.

**Comment by klinker41** [comment]
I wrote this library years and years ago as a freshman in college, so there are many different things I would do differently if I had time to improve it. However, that doesn't mean we should compound it with more confusing code than there already is.

**Comment by LoungeKatt** [comment]
@klinker41 Had it been presented that you were attempting to standardize the references, it would be a matter of saying it is less optimal but understandable. After all, the change was made. The lectures by your collaborator are an unnecessary component that add a condescending tone to an otherwise justified suggestion. That is between you and your team, though. Best of luck.

**Comment by klinker41** [comment]
You were the one who told him he was wrong, can't blame him for wanting to prove his point. I would have done the same and he has just as much right to the maintenance of this library as I do. I would always push for more readable code over the most optimal solution and continuously urge others to do the same.

**Comment by klinker24** [comment]
@LoungeKatt I never think that education and sharing experience is unnecessary, sorry you took it the wrong way. 

That is one of the main reasons I enjoy open source work and make it a priority to contribute back many of the things I create. Again, one of the main reasons to open source work, is for education purposes, that can be done in the comment section of an issue or PR too, just like this.

You simply tried to tell me that I was wrong, so I showed you that I was not wrong and that our opinion, on this matter, is the accepted one, by the vast majority. Just because I don't have the "owner" tag doesn't mean I cannot contribute to the discussion. I can merge or reject any pull requests just the same as Jake can...

**Comment by searchy2** [comment]
If it's any help, I've learned from this issue discussion! From now on, I will be using the provided constants for build versions in my projects. I have ran into the issue of forgetting what api 19 or 16 corresponds to and done at least 2-3 Bing queries to find out. Never had this problem when using the provided constants :grin: 
It is a bit tough to remember arbitrary numbers with everything else that has to be remembered in life!

**Comment by LoungeKatt** [comment]
@klinker41 Had I said he was wrong, I can understand proving a point. I agreed it was a fair point, but not necessarily relevant to the specific situation.

https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/Utils.java#L65
https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/Utils.java#L76
Both state quite clearly it is Marshmallow, so a comment would be unnecessary when the annotation, in a way, is also the comment. 

@klinker24 The impression came from elaborating on already clear statements by reiterating the same points at length. Bear in mind, you have every right to respond to anything addressed to or written about you and I don't consider that reiterating.

In the context of learning, Annotating API 23 on an explicitly documented Marshmallow method is actually informative. @searchy2 just proved this...

Anyway, I think this has been drawn out enough. The error has gone, so I will follow.

**Comment by klinker24** [comment]
So we agree that this is in fact a "best practice" then, despite you continuing to say that it was not. That is why I continued to educate. 

Wonderful and thank you @searchy2, that is exactly why I do this!

**Comment by LoungeKatt** [comment]
@klinker24 No. I agree it is best practice to avoid comments to explain the purpose of code when it could be unnecessary. I feel it is extraneous to comment comments. My point was that using an annotation as both an annotation and a comment is leveraging lint in a way that serves more than one purpose. Take it how you will. If you need to hear you were "right" then sure. In some context, given a specific purpose, outside the purpose of the library, you were right...

**Comment by klinker24** [comment]
Sigh. Lol. Thank you for your contribution.

**Pull request merged**
